# Generated by Django 5.1.5 on 2025-03-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_customuser_password_last_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
