# Generated by Django 5.1.7 on 2025-03-24 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('ethnicity', models.CharField(choices=[('Kikuyu', 'Kikuyu'), ('Luo', 'Luo'), ('Luhya', 'Luhya'), ('Kalenjin', 'Kalenjin'), ('Kamba', 'Kamba'), ('Other', 'Other')], max_length=20)),
                ('years_of_experience', models.IntegerField()),
                ('kcse_certificate', models.FileField(upload_to='driver_documents/')),
                ('good_conduct', models.FileField(upload_to='driver_documents/')),
                ('cover_letter', models.FileField(upload_to='driver_documents/')),
                ('cv', models.FileField(upload_to='driver_documents/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
