# Generated by Django 5.1.7 on 2025-03-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
